# golangci-lint configuration for tidbcloud-insight
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

issues:
  exclude-dirs:
    - bin
    - vendor
  exclude-files:
    - ".*_test\\.go$"
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet

linters-settings:
  gofmt:
    simplify: true
